### PR TITLE
Nick issue44 influx log mode events

### LINKED ISSUE #43: influx_log mode does not resolve the `latest` link
When run in the `influx_log` mode, the harness logs data points with "job_id=latest" in the tags. I believe the correct fix is to add logic to the influx_log mode that refuses to log links (only log directories).

For example, if you have a harness run that you want to identify a certain way on your file system, so you did something like `ln -s ./${harness-id} machine-failednode`, so that you could find it easily again, we don't want Influx logging it with `jobid=machine-failednode`.

### LINKED ISSUE #44: Influx event log incomplete when compute nodes don't have internet
When the compute nodes don't have internet access, events like binary_execute_{start,end}, check_{start,end} don't get reported to Influx.

A potential fix would be to have the `influx_log` mode log every event to influx when it logs the metrics, at the timestamp specified in each event file.

This would overwrite existing entries (like build_start), but since the timestamp should be the same, and the information should be the same, there shouldn't be any issues.

### LINKED ISSUE #49: Empty metrics RHS leads to harness crash with traceback
When a metrics file contains a line like: "metric =" (no space after the equals signs), the harness crashes and the following traceback is returned:

Traceback (most recent call last):
  File "/sw/acceptance/olcf-test-harness-07-20-2022/harness/bin/test_harness_driver.py", line 527, in <module>
    test_harness_driver()
  File "/sw/acceptance/olcf-test-harness-07-20-2022/harness/bin/test_harness_driver.py", line 487, in test_harness_driver
    Vargs.separate_build_stdio)
  File "/sw/acceptance/olcf-test-harness-07-20-2022/harness/bin/test_harness_driver.py", line 294, in auto_generated_scripts
    influx_reported = mymachine.log_to_influx()
  File "/sw/acceptance/olcf-test-harness-07-20-2022/harness/machine_types/base_machine.py", line 424, in log_to_influx
    exit_status = self._log_to_influx()
  File "/sw/acceptance/olcf-test-harness-07-20-2022/harness/machine_types/base_machine.py", line 507, in _log_to_influx
    return self.apptest._log_to_influx(self.apptest.get_harness_id())
  File "/sw/acceptance/olcf-test-harness-07-20-2022/harness/libraries/apptest.py", line 669, in _log_to_influx
    metrics = self._get_metrics(influx_machine_name, influx_app, influx_test)
  File "/sw/acceptance/olcf-test-harness-07-20-2022/harness/libraries/apptest.py", line 818, in _get_metrics
    if is_numeric(line[1]):
  File "/sw/acceptance/olcf-test-harness-07-20-2022/harness/libraries/apptest.py", line 789, in is_numeric
    if s[0] == '-':
IndexError: string index out of range

Fix: add a conditional in harness/libraries/apptest.py:787 to return False if len(s) == 0.

### LINKED ISSUE #50: Empty LHS metric leads to nameless metric being logged
While developing unit tests, I added a test that tests for properly handled bad metric lines. A line such as " = key_is_space" is treated the same as "= no_key" and results in the harness logging:
```
harness_unit_tests-test_bad_metrics_file-="no_key"
```
as a metric. This is invalid behavior, this metric should be ignored and a warning should be printed.

### LINKED ISSUE #51: Add environment variable to echo out Influx requests
Feature request. Would like an environment variable for testing and debugging which will process all of the influxDB data and do everything but send it to influx. If you don't set the RGT_INFLUX_URI or RGT_INFLUX_TOKEN, the data will never be processed.

Would like to add a RGT_INFLUX_NO_SEND wrap around each requests.post command for the Influx events and metrics.

### PR DESCRIPTION
**Pull request by hagertnl**
Refactored status_file.py to separate out Influx logging, make it callable from apptest.py

### CODE REVIEW

**Comment by hagertnl** [comment]
Addresses #44

**Comment by hagertnl** [comment]
Includes issue #43  fix

**Comment by hagertnl** [comment]
Addresses issue #49

**Comment by hagertnl** [comment]
Addresses issue #50

**Review by verolero86 — APPROVED** [review]
LGTM! Thank you @hagertnl 👍

**Pull request merged**
