### PR TITLE
Separate the InfluxDB logging into its own class

### LINKED ISSUE #84: Refactorization recommended in apptest.py, status_file.py, and the harness utilities
In the places using InfluxDB, there is a lot of common code that overlaps. I'd suggest creating a class that handles the InfluxDB transactions and is imported by apptest, status_file, and all harness utilities codes. A very simple API like:
```
influx_interface
    |- post_to_influx(post_body)
    |- run_flux_query(query)
    |- run_influxql_query(query)
```
would be all we need for a simple start.

### LINKED ISSUE #153: influx_log gives vague and unhelpful output
Running under `--mode influx_log` gives very vague output, like the following:
```
Using machine config: frontier.ini
Using machine config: frontier.ini
/lustre/orion/stf016/proj-shared/hagertnl/applications
Overriding tasks in inputfile since CLI mode was provided
runmodecmd =  ['influx_log']
self.__harness_task:  [['influx_log', None, None]]
reading harness config /sw/acceptance/olcf-test-harness/configs/frontier.ini
RGT_PATH_TO_SSPACE is already set. Skipping.
RGT_SYSTEM_LOG_TAG is already set. Skipping.
Starting tasks for Application.Test: coral2-lammps.test_0001node_17mil_reax: [['influx_log', None, None]]
Skipped 0, launched 1.
```

This is pretty unhelpful. More messages about what's going on by default would be appreciated.

### LINKED ISSUE #164: Refactor database logging backend
To prepare for other database logging, we need to abstract the InfluxDB logging code out of the harness core code.

Initial thoughts are that we can create a class called something like `db_logger`, which can enable multiple database backends simultaneously, and receives a dictionary of the test data (or metrics or nodescreen) that it logs to the respective databases.

This will enable us to go and add a Kafka database backend.

### PR DESCRIPTION
**Pull request by hagertnl**
This PR separates the InfluxDB logging functionality into its own class, governed by a generalized API to support other database interfaces being added in the future.

Closes #164 .

### CODE REVIEW

**Comment by hagertnl** [comment]
I am planning to pull all the post-run logging functionality from `--mode influx_log` into its own script in Utilities. I don't think this should be tied to a harness launch, as the `apptest.py` file where this is currently implemented is tied to a specific test id. We can look at implementing it in the `bin` directory instead of `utilities`, if that is preferred (there's next-to-no functional difference).

**Comment by hagertnl** [comment]
We could even merge with the `update_runs_from_slurm.py` functionality to just be an `update_remote_database.py`, and it automatically checks with the scheduler if it can't find event files.

**Comment by hagertnl** [comment]
I have confirmed that the events, metrics, and node health logging all work on unit tests. I would like to test further and confirm that all the environment variables we want are implemented, but I'm ready for feedback.

Asa mentioned that the file parsing we do inside the InfluxDB class (for output_txt in events, and for node locations for node health) should probably be pulled out, but I think we can hold off on refactoring that until we prove that Kafka will need the same information. If Kafka doesn't and that stuff is specific to InfluxDB, then it should probably stay in the InfluxDB class.

**Comment by hagertnl** [comment]
One feature to verify -- RGT_INFLUXDB_DISABLE=1 still works. I'm not certain that the correct dot-files will be created. I will check.

**Comment by hagertnl** [comment]
RGT_INFLUXDB_DISABLE is now working.

One item we need to address is the `influx_log` harness mode. I would suggest merging this functionality with the `update_runs_from_slurm.py` script, and integrating that script more with the harness classes.

**Comment by hagertnl** [comment]
At this point, my changes are done. AFAIK, this has nearly-identical functionality to what we have now, but by far more maintainable.

Change notes:
- Removed the `reason` field from InfluxDB logging. The usage of `reason` was for the `update_runs_from_slurm.py` script to use. However, we now use the `output_txt` field, since if `update_databases.py` needs to update a run, we know that the `check_end` didn't happen, so we can just use the `output_txt` field from that.
- Removed the update_entries_bulk_influxdb.py and change_machine_in_influx.py scripts. These are not needed. Their functionality can easily be derived from the other scripts (I can document the tricks for it).
- No more need for a `harness_keys.py` file to use most of the utilities! They operate out of the environment, just like the harness does
- InfluxDB functionality fully abstracted from the core harness code
- Multiple InfluxDB backends are supported for simultaneous logging

**Comment by hagertnl** [comment]
I'm tracking a new issue on Borg -- I had a nodescreen test that is failing to log to InfluxDB with the following message:
```
-----
Time: 2024-08-20 05:07:53,047
Logger: __main__
Loglevel: DEBUG
Message:
Posting node health data from test id: 1724144788.954787 to InfluxDB
-----

-----
Time: 2024-08-20 05:07:53,047
Logger: __main__
Loglevel: ERROR
Message:
The following exception occurred while logging node health results to https://harness-influxdb-prod-stf016.apps.marble.ccs.ornl.gov: __init__() missing 1 required positional argument: 'args'.
-----

-----
Time: 2024-08-20 05:07:53,047
Logger: __main__
Loglevel: DEBUG
Message:
Posting node health data from test id: 1724144788.954787 to InfluxDB
-----

-----
Time: 2024-08-20 05:07:53,048
Logger: __main__
Loglevel: ERROR
Message:
The following exception occurred while logging node health results to http://apps.marble.ccs.ornl.gov:31093: __init__() missing 1 required positional argument: 'args'.
-----

-----
Time: 2024-08-20 05:07:53,048
Logger: __main__
Loglevel: WARNING
Message:
Logging node_health failed to log to at least one database.
-----
```

I think this may be related to the database-related exceptions, so I'm going to re-do them to properly inherit from the Exception base class (and call the constructor of that) at the advice of Asa.

**Comment by hagertnl** [comment]
This error was because the node location file is non-existent! So the exception is to blame here. I need to fix how it's initialized.

**Comment by hagertnl** [comment]
I believe those are the only required fixes, but I'll check once we come back from maintenance.

**Comment by hagertnl** [comment]
After these latest fixes, the harness is properly handling the node screen on both Borg (`RGT_NODE_LOCATION_FILE` set to `none`) and Frontier (`RGT_NODE_LOCATION_FILE ` set to a file). If I do not set `RGT_NODE_LOCATION_FILE`, there is a sane error message printed.

**Comment by hagertnl** [comment]
I did use this version of the harness for all of my regression testing during yesterday's outage, and I did not hit any new issues beyond what I fixed above.

**Review by AcerP-py — APPROVED** [review]
LGTM

**Comment by hagertnl** [comment]
`update_databases.py` utility script does not respect the `--dry-run` flag. I'd like to fix this before merging.

**Review by ddietz89 — COMMENTED** [review]
LGTM

**Comment by hagertnl** [comment]
Dry-run functionality is implemented! I have tested using some dummy jobs that abort their jobs, and the messages are looking very good!

**Comment by hagertnl** [comment]
To follow up on later -- just got the new update_databases.py to crash with this:
```
+ set +x
[sauetest@login15.frontier 1725421424.7781916]$ ~/harness_automation/update_runs_wrapper_new.sh
+ update_databases.py --time 14d --user sauetest --machine frontier --loglevel DEBUG
Using machine config: frontier.ini
reading harness config /sw/acceptance/olcf-test-harness-dev/configs/frontier.ini
Using the following endpoint for InfluxDB health check and bucket verification: x.
Enabling the influxdb database logger from URL x.
Using the following endpoint for InfluxDB health check and bucket verification: x.
Enabling the influxdb database logger from URL x.
Enabled 2 database backends
Sending query: from(bucket: "accept") |> range(start: -14d)         |> filter(fn: (r) => r._measurement == "events" and r.machine == "frontier" and r._field != "output_txt")         |> last()         |> pivot(rowKey: ["test_id", "machine", "_time"], columnKey: ["_field"], valueColumn: "_value")         |> filter(fn: (r) => r.event_name == "job_queued" or (r.event_name != "check_end" and (r.event_value == "0" or r.event_value == "[NO_VALUE]")))         |> group() to: x.
Traceback (most recent call last):
  File "/sw/acceptance/olcf-test-harness-dev/harness/utilities/update_databases.py", line 248, in <module>
    results.extend(influxdb_get_results(db))
  File "/sw/acceptance/olcf-test-harness-dev/harness/utilities/update_databases.py", line 154, in influxdb_get_results
    if not e in r.keys():
AttributeError: 'str' object has no attribute 'keys'
+ set +x
```
Also need to add functionality to log to just a single database, instead of all of them, in case where a test is not in all databases.

**Comment by hagertnl** [comment]
This error appears to have happened because the database changed while running the update script. There's not really any locking mechanism that we can use to handle this, since we're interacting with the database through HTTP protocol, and not interactive sessions or anything like that. I think we will just have to document that limitation.

I still need to add functionality for logging to a single database, instead of all databases.

**Comment by hagertnl** [comment]
Okay, I'm coming up for air now -- I believe I have the 3 main DB utilities all translated to use the new database API. Test jobs are still successful, so I believe everything is working as expected. I am pulling down the latest commits to `/sw/acceptance/olcf-test-harness-dev` on Mod now. Feel free to test.

**Comment by hagertnl** [comment]
One crash from last night that needs to be fixed:
```
Using machine config: frontier.ini
reading harness config /sw/acceptance/olcf-test-harness-dev/configs/frontier.ini
Traceback (most recent call last):
  File "/sw/acceptance/olcf-test-harness-dev/harness/utilities/update_databases.py", line 374, in <module>
    db_logger=single_db_logger)
TypeError: make_subtest() got an unexpected keyword argument 'db_logger'
```
This came up while running the `update_databases.py` script. Appears to be an edge case.

**Comment by hagertnl** [comment]
Fixed the latest issue now. Forgot to add the db_logger argument to the subtest factory.

**Comment by hagertnl** [comment]
One feature I want to add to `update_databases.py` -- have a build timeout where if the harness finds a `build_start` that is greater than maybe 6 hours old, it logs a `build_end` event with value 23 to indicate that the build timed out and was probably cancelled. This could help clean up the DB entries some. @ddietz89 thoughts?

**Comment by ddietz89** [comment]
> One feature I want to add to `update_databases.py` -- have a build timeout where if the harness finds a `build_start` that is greater than maybe 6 hours old, it logs a `build_end` event with value 23 to indicate that the build timed out and was probably cancelled. This could help clean up the DB entries some. @ddietz89 thoughts?

6 hours seems like a reasonable cut off to me. I do have a couple tests that can take 2 (maybe one even at 3 hours?) but still at 6 hours should be plenty.

**Pull request merged**
