### PR TITLE
Add validation to input file parameters

### LINKED ISSUE #33: Long stack trace printed when test name is invalid
When the rgt.inp file specifies an undefined test (for example, if you developed a new test on another machine and forgot to push the changes), the harness currently prints a long and unhelpful stack trace:
```
Traceback (most recent call last):
  File "/sw/acceptance/olcf-test-harness/harness/bin/test_harness_driver.py", line 524, in <module>
    test_harness_driver()
  File "/sw/acceptance/olcf-test-harness/harness/bin/test_harness_driver.py", line 469, in test_harness_driver
    jstatus.initialize_subtest(launch_id, unique_id)
  File "/sw/acceptance/olcf-test-harness/harness/libraries/status_file.py", line 305, in initialize_subtest
    event_time = self.log_event(StatusFile.EVENT_LOGGING_START)
  File "/sw/acceptance/olcf-test-harness/harness/libraries/status_file.py", line 348, in log_event
    event_type, event_subtype, str(event_value))
  File "/sw/acceptance/olcf-test-harness/harness/libraries/status_file.py", line 512, in __log_event
    event_time, event_filename)
  File "/sw/acceptance/olcf-test-harness/harness/libraries/status_file.py", line 688, in get_status_info
    'harness function being executed from wrong directory.')
AssertionError: harness function being executed from wrong directory.
```

### LINKED ISSUE #34: Long stack trace printed when Scripts directory does not exist in a test
If the `Scripts` subdirectory does not exist, the user is confronted with a confusing and long message:

```
/bin/sh: line 0: cd: /ccs/proj/stf016/hagertnl/harness/crusher/applications/harness_unit_tests/test_no_scripts_dir/Scripts: No such file or directory
Using machine config: crusher.ini
reading harness config /sw/acceptance/olcf-test-harness-influx-dev/configs/crusher.ini
RGT_MACHINE_NAME is already set. Skipping.
RGT_MACHINE_TYPE is already set. Skipping.
RGT_SCHEDULER_TYPE is already set. Skipping.
RGT_JOBLAUNCHER_TYPE is already set. Skipping.
RGT_CPUS_PER_NODE is already set. Skipping.
RGT_GPUS_PER_NODE is already set. Skipping.
RGT_SUBMIT_QUEUE is already set. Skipping.
RGT_SUBMIT_ARGS is already set. Skipping.
RGT_NCCS_TEST_HARNESS_MODULE is already set. Skipping.
RGT_TYPE_OF_REPOSITORY is already set. Skipping.
RGT_GIT_REPS_BRANCH is already set. Skipping.
RGT_GIT_DATA_TRANSFER_PROTOCOL is already set. Skipping.
RGT_GIT_MACHINE_NAME is already set. Skipping.
RGT_GIT_SERVER_APPLICATION_PARENT_DIR is already set. Skipping.
RGT_GIT_SSH_SERVER_URL is already set. Skipping.
RGT_GIT_HTTPS_SERVER_URL is already set. Skipping.
RGT_PATH_TO_SSPACE is already set. Skipping.
RGT_SYSTEM_LOG_TAG is already set. Skipping.
RGT_ACCT_ID is already set. Skipping.
Using launch id: crusher_test/hagertnl@2022-07-14T13:44:57.54
Generated test unique id: 1657820820.5605283
Traceback (most recent call last):
  File "/sw/acceptance/olcf-test-harness-influx-dev/harness/bin/test_harness_driver.py", line 527, in <module>
    test_harness_driver()
  File "/sw/acceptance/olcf-test-harness-influx-dev/harness/bin/test_harness_driver.py", line 472, in test_harness_driver
    jstatus.initialize_subtest(launch_id, unique_id)
  File "/sw/acceptance/olcf-test-harness-influx-dev/harness/libraries/status_file.py", line 311, in initialize_subtest
    event_time = self.log_event(StatusFile.EVENT_LOGGING_START)
  File "/sw/acceptance/olcf-test-harness-influx-dev/harness/libraries/status_file.py", line 354, in log_event
    event_type, event_subtype, str(event_value))
  File "/sw/acceptance/olcf-test-harness-influx-dev/harness/libraries/status_file.py", line 521, in __log_event
    event_time, event_filename)
  File "/sw/acceptance/olcf-test-harness-influx-dev/harness/libraries/status_file.py", line 778, in get_status_info
    'harness function being executed from wrong directory.')
AssertionError: harness function being executed from wrong directory.
In function subtest._start_test we have a critical error.
The command 'test_harness_driver.py -r -l crusher_test/hagertnl@2022-07-14T13:44:57.54' has exited with a failure.
The exit return value is 1
.
Application harness_unit_tests future exception:
Command failed: test_harness_driver.py -r -l crusher_test/hagertnl@2022-07-14T13:44:57.54
```
This error appears to be detected before the run, and not treated as fatal. It should be treated as fatal.

### LINKED ISSUE #75: Forgetting to put the app name in rgt.inp leads to out-of-range error
A line that forgets either the test or app name in rgt.inp will be confronted with an out-of-range error. That should be made more user-friendly.

### PR DESCRIPTION
**Pull request by hagertnl**
Also adding short-circuiting capability so that the harness doesn't try to create paths all of it's log files if it doesn't even read the input file in correctly.

### CODE REVIEW

**Comment by hagertnl** [comment]
Fixes #75 . Other fixes inbound.

**Comment by hagertnl** [comment]
New behavior -- if one line in the input file is invalid, the entire harness launch will abort with about 5 lines of stdout. For example, if I forget to include the app or test name, and one line is too short, the user will see:
```
Using machine config: crusher.ini
Using machine config: crusher.ini
Invalid number of words in test line: Test = harness_unit_tests

ERROR: Failed to parse input file.
2023-04-28 16:41:29,449 - main_logger - ERROR - No tests found in input file. Aborting.
```

**Comment by hagertnl** [comment]
Expected to fix issues #33 , #34 , and #75 . Also added validation to the application name, which was not currently reported as an open issue, but would appear in the case of a typo.

The loglevel discussion needs to be elevated. Currently, to figure out what happens to a run, you have to look in `harness_log_files.{timestamp}/{app}/{app}__{test}.logfile.txt`, which is not very user-friendly. The explanations are fairly short-winded, and I would like to see them printed to the console, if the user specifies `--loglevel WARNING`, for example. I've filed an issue about this as Issue #102 , since this doesn't only affect this PR.

**Comment by hagertnl** [comment]
This issue also contains the fixes from PR #98 , since that PR added a logger to the apptest_layout class.

**Review by ddietz89 — APPROVED** [review]

**Pull request merged**
