### PR TITLE
Add launch id and run count to test status file

### PR DESCRIPTION
**Pull request by MichaelBrim**
Addresses Issue #16 

Adds two new columns to the `<app>/<test>/Status/rgt_status.txt` files, 'Launch ID' and 'Run Count', to help track resubmissions. The launch id is a timestamp from when `runtests.py` was invoked. The run count is a ratio given as `submit_count/max_submissions`

To take advantage of the new resubmission tracking capability, the test's job script epilog should be updated to use:
`test_harness_driver.py -l __launch_id__ -r __max_submissions__`

### CODE REVIEW

**Comment by MichaelBrim** [comment]
Here is an example of the new status file format, which I generated using two launches, one with max=2, and one with max=5:
```
> cat ../Status/rgt_status.txt
#######################################################################################################################################################

# Start Time                   Launch ID          Unique ID             Run Count  Batch Job ID         Build Status    Submit Status   Check Status

#######################################################################################################################################################
2021-12-02T17:22:44.872442     20211202_172244    1638483764.8369894    1/2        301983               0               0               0
2021-12-02T17:23:28.263520     20211202_172244    1638483808.2573292    2/2        301984               0               0               0
2021-12-02T17:25:20.070694     20211202_172519    1638483920.036623     1/5        301985               0               0               0
2021-12-02T17:26:03.529024     20211202_172519    1638483963.5227036    2/5        301986               0               0               0
2021-12-02T17:26:45.356868     20211202_172519    1638484005.3532786    3/5        301987               0               0               0
2021-12-02T17:27:26.610925     20211202_172519    1638484046.6075735    4/5        301989               0               0               0
2021-12-02T17:28:08.456475     20211202_172519    1638484088.4509869    5/5        301990               0               0               0
```

**Comment by verolero86** [comment]
@MichaelBrim to update to include ID for user and system_log_tag and 2 more timestamp digits.
Breaks dashboard but @ddietz89 will take a look

**Comment by MichaelBrim** [comment]
The launch id string now includes the testshot system_log_tag and the username.

Here's the updated example:
```
####################################################################################################################################################################################

# Start Time                 Launch ID                                          Unique ID            Run Count  Batch Job ID         Build Status    Submit Status   Check Status

####################################################################################################################################################################################
2021-12-16T12:49:35.346206   spock_test/mjbrim@2021-12-16T12:49:35.16           1639676975.3344657   1/3        305149               0               0               0
2021-12-16T12:50:19.080106   spock_test/mjbrim@2021-12-16T12:49:35.16           1639677019.073456    2/3        305151               0               0               0
2021-12-16T12:51:00.986649   spock_test/mjbrim@2021-12-16T12:49:35.16           1639677060.9797184   3/3        305152               0               0               0
```

**Review by verolero86 — APPROVED** [review]
Thanks for adding this new fields to the status field @MichaelBrim ! LGTM!

**Pull request merged**
