### PR TITLE
Log level NOTSET is default and extremely verbose

### LINKED ISSUE #156: test_harness_driver.py does not recognize NOTSET as a log level
`runtests.py` -- not explicitly setting a log level leads to this message:

```
usage: test_harness_driver.py [-h] [-b] [-sb] [-c] [-C CONFIGFILE]
                              [-d SCRIPTSDIR] [-i UNIQUEID] [-l LAUNCHID]
                              [--loglevel {DEBUG,debug,INFO,info,WARNING,warning,ERROR,error,CRITICAL,critical}]
                              [-r [RESUBMIT]] [-R] [-s]
test_harness_driver.py: error: argument --loglevel: invalid choice: 'NOTSET' (choose from 'DEBUG', 'debug', 'INFO', 'info', 'WARNING', 'warning', 'ERROR', 'error', 'CRITICAL', 'critical')
In function subtest._start_test we have a critical error.
The command 'test_harness_driver.py -r -l frontier_test/hagertnl@2023-12-27T11:53:01.49 --loglevel NOTSET' has exited with a failure.
```

This is because of this chain of commands:
1. `runtests.py` -- when not given a loglevel, defaults it to the string `NOTSET` (Python `logging` should disable any filtering going on when set to `NOTSET`)
2. `apptest.py` calls `test_harness_driver.py` and supplies the loglevel flag as `--loglevel {self.__log_level}`, which is `NOTSET`, which is not a valid option for `test_harness_driver.py`.

So we have 2 possible solutions -- (1) add `NOTSET` as an option in `test_harness_driver.py` or (2) set a different default value in `runtests.py`, such as `WARNING` (or both)

I'm in favor of doing both actually, since `NOTSET` is an option for the Python `logging` class that the RGT logger is built upon, we should implement that. But `NOTSET` will also be *very* wordy by default, so I think we may want to use a higher loglevel as our default loglevel

### PR DESCRIPTION
**Pull request by hagertnl**
Key changes:
- Changed default from NOTSET to WARNING for both runtests.py and test_harness_driver.py (will usually inherit from runtests.py)
- Added NOTSET as a valid option in test_harness_driver.py.

Fixes #156

### CODE REVIEW

**Comment by hagertnl** [comment]
The default output of launching a test now looks like:
```
Using machine config: frontier.ini
Using machine config: frontier.ini
/ccs/proj/stf016/hagertnl/harness/unit_tests
Overriding tasks in inputfile since CLI mode was provided
runmodecmd =  ['start', 'stop']
self.__harness_task:  [['start_tests', None, None]]
self.__harness_task:  [['start_tests', None, None], ['stop_tests', None, None]]
reading harness config /lustre/orion/proj-shared/stf016/hagertnl/Scratch/harness-dev/olcf-test-harness-fork/configs/frontier.ini
RGT_PATH_TO_SSPACE is already set. Skipping.
Starting tasks for Application.Test: harness_unit_tests.test_successful_run: [['start_tests', None, None], ['stop_tests', None, None]]
Using machine config: frontier.ini
reading harness config /lustre/orion/proj-shared/stf016/hagertnl/Scratch/harness-dev/olcf-test-harness-fork/configs/frontier.ini
RGT_MACHINE_NAME is already set. Skipping.
RGT_MACHINE_TYPE is already set. Skipping.
RGT_SCHEDULER_TYPE is already set. Skipping.
RGT_JOBLAUNCHER_TYPE is already set. Skipping.
RGT_CPUS_PER_NODE is already set. Skipping.
RGT_GPUS_PER_NODE is already set. Skipping.
RGT_BATCH_QUEUE is already set. Skipping.
RGT_PROJECT_ID is already set. Skipping.
RGT_SUBMIT_ARGS is already set. Skipping.
RGT_NCCS_TEST_HARNESS_MODULE is already set. Skipping.
RGT_TYPE_OF_REPOSITORY is already set. Skipping.
RGT_GIT_REPS_BRANCH is already set. Skipping.
RGT_GIT_DATA_TRANSFER_PROTOCOL is already set. Skipping.
RGT_GIT_MACHINE_NAME is already set. Skipping.
RGT_GIT_SERVER_APPLICATION_PARENT_DIR is already set. Skipping.
RGT_GIT_SSH_SERVER_URL is already set. Skipping.
RGT_GIT_HTTPS_SERVER_URL is already set. Skipping.
RGT_PATH_TO_SSPACE is already set. Skipping.
RGT_SYSTEM_LOG_TAG is already set. Skipping.
Using launch id: frontier_test/hagertnl@2024-01-04T08:17:28.20
Generated test unique id: 1704374248.3718657
Creating machine frontier: Type = linux_x86_64 ; Scheduler = slurm ; Job launcher = srun
Creating scheduler
Creating jobLauncher
RGT Test Parameters - Builtin
=============================
job_name = test_successful_run
nodes = 1
total_processes = 1
walltime = 1
executable_path = ./dummy
batch_filename = run.sh
build_cmd = ./build_success.sh
check_cmd = ./check.sh
report_cmd = ./report.sh
resubmit = 1
RGT Test Parameters - User
==========================
WARNING: Ignoring invalid built-in parameter key launch_id
Submitting job from SLURM class using batchfilename run.sh
sbatch  -p batch  -A stf016 run.sh
SLURM jobID =  1559981
Launched 1 tests, skipped 0 tests.
```

**Comment by hagertnl** [comment]
@ddietz89 should be good to go now.

**Comment by hagertnl** [comment]
This is the new output:
```
Using machine config: frontier.ini
Using machine config: frontier.ini
/ccs/proj/stf016/hagertnl/harness/unit_tests
Overriding tasks in inputfile since CLI mode was provided
runmodecmd =  ['start', 'stop']
self.__harness_task:  [['start_tests', None, None]]
self.__harness_task:  [['start_tests', None, None], ['stop_tests', None, None]]
reading harness config /lustre/orion/proj-shared/stf016/hagertnl/Scratch/harness-dev/olcf-test-harness-fork/configs/frontier.ini
RGT_PATH_TO_SSPACE is already set. Skipping.
Starting tasks for Application.Test: harness_unit_tests.test_successful_run: [['start_tests', None, None], ['stop_tests', None, None]]
Using machine config: frontier.ini
reading harness config /lustre/orion/proj-shared/stf016/hagertnl/Scratch/harness-dev/olcf-test-harness-fork/configs/frontier.ini
RGT_MACHINE_NAME is already set. Skipping.
RGT_MACHINE_TYPE is already set. Skipping.
RGT_SCHEDULER_TYPE is already set. Skipping.
RGT_JOBLAUNCHER_TYPE is already set. Skipping.
RGT_CPUS_PER_NODE is already set. Skipping.
RGT_GPUS_PER_NODE is already set. Skipping.
RGT_BATCH_QUEUE is already set. Skipping.
RGT_PROJECT_ID is already set. Skipping.
RGT_SUBMIT_ARGS is already set. Skipping.
RGT_NCCS_TEST_HARNESS_MODULE is already set. Skipping.
RGT_TYPE_OF_REPOSITORY is already set. Skipping.
RGT_GIT_REPS_BRANCH is already set. Skipping.
RGT_GIT_DATA_TRANSFER_PROTOCOL is already set. Skipping.
RGT_GIT_MACHINE_NAME is already set. Skipping.
RGT_GIT_SERVER_APPLICATION_PARENT_DIR is already set. Skipping.
RGT_GIT_SSH_SERVER_URL is already set. Skipping.
RGT_GIT_HTTPS_SERVER_URL is already set. Skipping.
RGT_PATH_TO_SSPACE is already set. Skipping.
RGT_SYSTEM_LOG_TAG is already set. Skipping.
Using launch id: frontier_test/hagertnl@2024-01-04T10:54:29.12
Generated test unique id: 1704383669.2974172
Creating machine frontier: Type = linux_x86_64 ; Scheduler = slurm ; Job launcher = srun
Creating scheduler
Creating jobLauncher
RGT Test Parameters - Builtin
=============================
job_name = test_successful_run
nodes = 1
total_processes = 1
walltime = 1
executable_path = ./dummy
batch_filename = run.sh
build_cmd = ./build_success.sh
check_cmd = ./check.sh
report_cmd = ./report.sh
resubmit = 1
RGT Test Parameters - User
==========================
Path to Source: /autofs/nccs-svm1_proj/stf016/hagertnl/harness/unit_tests/harness_unit_tests/Source
Path to Build: /lustre/orion/proj-shared/stf016/hagertnl/harness_sspace/frontier/01.04.24-10.54/harness_unit_tests/test_successful_run/1704383669.2974172/build_directory
WARNING: Ignoring invalid built-in parameter key launch_id
Submitting job from SLURM class using batchfilename run.sh
sbatch  -p batch  -A stf016 run.sh
SLURM jobID =  1560215
Launched 1 tests, skipped 0 tests.
```

**Review by ddietz89 — APPROVED** [review]
Awesome!

**Pull request merged**
